In [40]:
import polars as pl
df2021=pl.read_csv("D:\\DEPI\\tedsa_puf_2021.csv")
df2022=pl.read_csv("D:\\DEPI\\tedsa_puf_2022.csv")
df2023=pl.read_csv("D:\\DEPI\\tedsa_puf_2023.csv")

In [41]:
all_data = pl.concat(
    [df2021, df2022, df2023],
    how="vertical"
)

all_data.write_parquet(
    "tedsa_2021_2023.parquet"
)

In [42]:
all_data = all_data.with_columns(
    pl.all().replace(-9, None)
)

In [43]:
all_data.null_count()

shape: (1, 62)
┌───────┬────────┬────────┬────────┬───┬────────┬────────┬─────────┬──────────┐
│ ADMYR ┆ CASEID ┆ STFIPS ┆ EDUC   ┆ … ┆ REGION ┆ IDU    ┆ ALCDRUG ┆ CBSA2020 │
│ ---   ┆ ---    ┆ ---    ┆ ---    ┆   ┆ ---    ┆ ---    ┆ ---     ┆ ---      │
│ u32   ┆ u32    ┆ u32    ┆ u32    ┆   ┆ u32    ┆ u32    ┆ u32     ┆ u32      │
╞═══════╪════════╪════════╪════════╪═══╪════════╪════════╪═════════╪══════════╡
│ 0     ┆ 0      ┆ 0      ┆ 909507 ┆ … ┆ 0      ┆ 926546 ┆ 0       ┆ 1783703  │
└───────┴────────┴────────┴────────┴───┴────────┴────────┴─────────┴──────────┘

In [44]:
all_data = all_data.drop_nulls(
    subset=["SUB1"]
)

all_data.null_count()

shape: (1, 62)
┌───────┬────────┬────────┬────────┬───┬────────┬────────┬─────────┬──────────┐
│ ADMYR ┆ CASEID ┆ STFIPS ┆ EDUC   ┆ … ┆ REGION ┆ IDU    ┆ ALCDRUG ┆ CBSA2020 │
│ ---   ┆ ---    ┆ ---    ┆ ---    ┆   ┆ ---    ┆ ---    ┆ ---     ┆ ---      │
│ u32   ┆ u32    ┆ u32    ┆ u32    ┆   ┆ u32    ┆ u32    ┆ u32     ┆ u32      │
╞═══════╪════════╪════════╪════════╪═══╪════════╪════════╪═════════╪══════════╡
│ 0     ┆ 0      ┆ 0      ┆ 264292 ┆ … ┆ 0      ┆ 137940 ┆ 0       ┆ 1235164  │
└───────┴────────┴────────┴────────┴───┴────────┴────────┴─────────┴──────────┘

In [45]:
important_columns = [
    "ADMYR",
    "AGE",
    "SEX",
    "SUB1",
    "ROUTE1",
    "FREQ1",
    "FRSTUSE1",
    "SERVICES",
    "PSYPROB",
    "STFIPS",
    "RACE",
    "ETHNIC",
    "EDUC",
    "EMPLOY",
    "MARSTAT",
    "PSOURCE",
    "PRIMPAY",
    "HLTHINS",
    "DAYWAIT",
    "DSMCRIT",
    "SUB2",
    "SUB3",
    "ALCFLG",
    "MARFLG",
    "COKEFLG",
    "HERFLG",
    "METHFLG",
    "BENZFLG",
    "OTHERFLG",
    "VET"
]

all_data=all_data.select(important_columns)

In [46]:
all_data

shape: (3_947_784, 30)
┌───────┬─────┬─────┬──────┬───┬─────────┬─────────┬──────────┬─────┐
│ ADMYR ┆ AGE ┆ SEX ┆ SUB1 ┆ … ┆ METHFLG ┆ BENZFLG ┆ OTHERFLG ┆ VET │
│ ---   ┆ --- ┆ --- ┆ ---  ┆   ┆ ---     ┆ ---     ┆ ---      ┆ --- │
│ i64   ┆ i64 ┆ i64 ┆ i64  ┆   ┆ i64     ┆ i64     ┆ i64      ┆ i64 │
╞═══════╪═════╪═════╪══════╪═══╪═════════╪═════════╪══════════╪═════╡
│ 2021  ┆ 6   ┆ 1   ┆ 2    ┆ … ┆ 0       ┆ 0       ┆ 0        ┆ 2   │
│ 2021  ┆ 2   ┆ 2   ┆ 4    ┆ … ┆ 0       ┆ 0       ┆ 1        ┆ 2   │
│ 2021  ┆ 6   ┆ 2   ┆ 4    ┆ … ┆ 0       ┆ 0       ┆ 0        ┆ 2   │
│ 2021  ┆ 5   ┆ 2   ┆ 5    ┆ … ┆ 0       ┆ 0       ┆ 0        ┆ 2   │
│ 2021  ┆ 5   ┆ 2   ┆ 5    ┆ … ┆ 0       ┆ 0       ┆ 0        ┆ 2   │
│ …     ┆ …   ┆ …   ┆ …    ┆ … ┆ …       ┆ …       ┆ …        ┆ …   │
│ 2023  ┆ 7   ┆ 2   ┆ 4    ┆ … ┆ 0       ┆ 0       ┆ 0        ┆ 2   │
│ 2023  ┆ 9   ┆ 1   ┆ 2    ┆ … ┆ 0       ┆ 0       ┆ 0        ┆ 2   │
│ 2023  ┆ 4   ┆ 1   ┆ 4    ┆ … ┆ 0       ┆ 0       ┆ 0        ┆ 2   │
│ 2023  ┆ 10  ┆ 2   ┆ 2    ┆ … ┆ 0       ┆ 0       ┆ 0        ┆ 2   │
│ 2023  ┆ 7   ┆ 1   ┆ 2    ┆ … ┆ 0       ┆ 0       ┆ 0        ┆ 2   │
└───────┴─────┴─────┴──────┴───┴─────────┴─────────┴──────────┴─────┘

In [47]:
print(all_data.columns)

['ADMYR', 'AGE', 'SEX', 'SUB1', 'ROUTE1', 'FREQ1', 'FRSTUSE1', 'SERVICES', 'PSYPROB', 'STFIPS', 'RACE', 'ETHNIC', 'EDUC', 'EMPLOY', 'MARSTAT', 'PSOURCE', 'PRIMPAY', 'HLTHINS', 'DAYWAIT', 'DSMCRIT', 'SUB2', 'SUB3', 'ALCFLG', 'MARFLG', 'COKEFLG', 'HERFLG', 'METHFLG', 'BENZFLG', 'OTHERFLG', 'VET']

In [48]:
print(all_data.shape)

(3947784, 30)